//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int Id { get; set; }
        public string ПІБ_Клієнта { get; set; }
        public string Країна { get; set; }
        public string Додаткові_послуги { get; set; }
        public Nullable<int> Ціна { get; set; }
        public string Дата_виїзду { get; set; }
        public string Дата_повернення { get; set; }
        public string Тур { get; set; }
    }
}
