//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tours
    {
        public int Id { get; set; }
        public string Країна { get; set; }
        public string Назва_туру { get; set; }
        public Nullable<int> Ціна { get; set; }
    }
}
